name: "go-web"
version: "1.0"
mode: "debug"
port: 8080
start_time: "2024-07-01"
machine_id: 1

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  database: "gin-forum"
  max_idle: 10
  max_open: 10

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  pool_size: 10

log:
  level: "debug"
  filename: "./logger/test.log"
  max_size: 100
  max_backups: 10
  max_age: 30
